name: DeathDropPercent
author: MrQuackDuck
version: '${project.version}'
main: net.justempire.deathdroppercent.DeathDropPercent
api-version: '1.16'
commands:
  deathdroppercent:
    permission: deathdroppercent.admin
    aliases:
      - ddc