name: DeathDropPercent
author: MrQuackDuck
version: '1.0'
main: net.justempire.deathdroppercent.DeathDropPercent
api-version: '1.20'
commands:
  deathdroppercent:
    permission: deathdroppercent.admin
    aliases:
      - ddc