name: DeathDropPercent
author: MrQuackDuck
version: '1.3'
main: net.justempire.deathdroppercent.DeathDropPercent
api-version: '1.16'
commands:
  deathdroppercent:
    permission: deathdroppercent.admin
    aliases:
      - ddc

permissions:
  deathdroppercent.admin:
    description: Allows to use /ddc command
    default: op
  deathdroppercent.drop:
    description: Is player permitted to drop items on death?
    default: true